version: 2
jobs:
   build-linux:
     working_directory: ~/please
     docker:
       - image: thoughtmachine/please-servers:20200828
     environment:
       PLZ_CONFIG_PROFILE: "ci"
     steps:
       - checkout
       - restore_cache:
           key: go-linux-main-v5-{{ checksum "third_party/go/BUILD" }}
       - run:
           name: Test
           command: ./pleasew test -p -v 2 --exclude //tests/...
       - store_test_results:
           path: plz-out/results
       - run:
           name: Package
           command: ./pleasew build //elan //mettle //zeal //flair //lucidity //purity //discern //scripts:gen_release -p --profile ci -v 2
       - persist_to_workspace:
           root: plz-out/bin
           paths:
             - discern/discern
             - elan/elan
             - flair/flair
             - lucidity/lucidity
             - mettle/mettle
             - purity/purity
             - zeal/zeal
             - scripts/gen_release.pex
       - store_artifacts:
           path: plz-out/log
       - save_cache:
           key: go-linux-main-v5-{{ checksum "third_party/go/BUILD" }}
           paths: [ ".plz-cache/third_party/go" ]

   release:
     docker:
       - image: thoughtmachine/please_docs:20190318
     steps:
       - attach_workspace:
           at: /tmp/workspace
       - run: /tmp/workspace/scripts/gen_release.pex /tmp/workspace/elan/elan /tmp/workspace/flair/flair /tmp/workspace/mettle/mettle /tmp/workspace/purity/purity /tmp/workspace/zeal/zeal /tmp/workspace/lucidity/lucidity /tmp/workspace/discern/discern

workflows:
  version: 2
  build-all:
    jobs:
      - build-linux
      - release:
          requires:
            - build-linux
          filters:
            branches:
              only: master
